stages:
  - test
  - release
variables:
  GIT_SSL_NO_VERIFY: "true"
Test:
  stage: test
  script:
   - .\build.ps1 -Tasks "analyze","test"
  except:
    - master
Release:
  stage: release
  script:
    - .\build.ps1 -Tasks "analyze","test","release"
  only:
    -master